coverage_service: html
xcodeproj: MVVMArchitectureTemplate.xcodeproj
workspace: MVVMArchitectureTemplate.xcworkspace
scheme: MVVMArchitectureTemplate
source_directory: MVVMArchitectureTemplate
output_directory: slather_html_report
ignore:
  - "MVVMArchitectureTemplate/Presentation/*"
  - "MVVMArchitectureTemplate/Resources/*"
  - SourcePackages/*
  - "**/*Builder.swift"
  - "**/AppDelegate.swift"
  - "**/SceneDelegate.swift"
  - "../Library/Developer/Xcode/DerivedData/*"
  - "../../Library/Developer/Xcode/DerivedData/*"
  - "../../../Library/Developer/Xcode/DerivedData/*"
  - "../../../../Library/Developer/Xcode/DerivedData/*"
  - "../../../../../Library/Developer/Xcode/DerivedData/*"