coverage_service: html
xcodeproj: MVVMArchitectureTemplate.xcodeproj
workspace: MVVMArchitectureTemplate.xcworkspace
scheme: MVVMArchitectureTemplate
source_directory: MVVMArchitectureTemplate
output_directory: slather_html_report
ignore:
  - "MVVMArchitectureTemplate/Resources/*"
  - "MVVMArchitectureTemplate/Presentation/Container/*"
  - "MVVMArchitectureTemplate/Presentation/Core/*"
  - "MVVMArchitectureTemplate/Utility/UIHelper/*"
  - "**/*Cell.swift"
  - "**/*View.swift"
  - "**/*ViewController.swift"
  - "**/*Routing.swift"
  - "**/*Style.swift"
  - "**/*+Modifier.swift"
  - "**/*Builder.swift"
  - "**/AppDelegate.swift"
  - "**/SceneDelegate.swift"
  - "../Library/Developer/Xcode/DerivedData/*"
  - "../../Library/Developer/Xcode/DerivedData/*"
  - "../../../Library/Developer/Xcode/DerivedData/*"
  - "../../../../Library/Developer/Xcode/DerivedData/*"
  - "../../../../../Library/Developer/Xcode/DerivedData/*"
  - SourcePackages/*