name: MVVMArchitectureTemplate

options:
  bundleIdPrefix: com.yossibank
  developmentLanguage: ja
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
  configs:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.6.0
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs.git
    from: 9.1.0
  ios-snapshot-test-case:
    url: https://github.com/uber/ios-snapshot-test-case
    from: 8.0.0

targets:
  MVVMArchitectureTemplate:
    type: application
    platform: iOS
    sources:
      - MVVMArchitectureTemplate
    settings:
      base:
        DEVELOPMENT_LANGUAGE: jp
        INFOPLIST_FILE: MVVMArchitectureTemplate/App/Plist/Info.plist
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        debug:
          OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=500
          PRODUCT_BUNDLE_IDENTIFIER: com.yossibank.MVVMArchitectureTemplate.dev
        release:
          PRODUCT_BUNDLE_IDENTIFIER: com.yossibank.MVVMArchitectureTemplate
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAnalyticsWithoutAdIdSupport
      - package: firebase-ios-sdk
        product: FirebaseCrashlytics
      - package: SnapKit
    preBuildScripts:
      - path: ./Scripts/Firebase/infoplist.sh
        name: Setup GoogleServiceInfoPlist
        basedOnDependencyAnalysis: false
      - path: ./Scripts/XcodeGen/licensePlist.sh
        name: Setup LicensePlist
        basedOnDependencyAnalysis: false
      - path: ./Scripts/XcodeGen/mockolo.sh
        name: Generate Mock
        basedOnDependencyAnalysis: false
        outputFiles:
          - MVVMArchitectureTemplateTests/TestMock/MockResults.swift
      - path: ./Scripts/XcodeGen/swiftformat.sh
        name: Run SwiftFormat
        basedOnDependencyAnalysis: false
      - path: ./Scripts/XcodeGen/swiftgen.sh
        name: Run SwiftGen
        basedOnDependencyAnalysis: false
    postCompileScripts:
      - path: ./Scripts/XcodeGen/swiftlint.sh
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - path: ./Scripts/Firebase/crashlytics.sh
        name: Run Crashlytics
        basedOnDependencyAnalysis: false
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

  MVVMArchitectureTemplateTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MVVMArchitectureTemplateTests
    settings:
      base:
        INFOPLIST_FILE: MVVMArchitectureTemplateTests/Info.plist
    dependencies:
      - target: MVVMArchitectureTemplate
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
      - package: ios-snapshot-test-case
        product: iOSSnapshotTestCase

  MVVMArchitectureTemplateUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MVVMArchitectureTemplateUITests
    settings:
      base:
        INFOPLIST_FILE: MVVMArchitectureTemplateUITests/Info.plist
    dependencies:
      - target: MVVMArchitectureTemplate

schemes:
  MVVMArchitectureTemplate:
    build:
      targets:
        MVVMArchitectureTemplate: all
        MVVMArchitectureTemplateTests: [test]
        MVVMArchitectureTemplateUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-FIRDebugEnabled": false
        "-FIRDebugDisabled": true
        "-FIRAnalyticsDebugEnabled": false
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: MVVMArchitectureTemplateTests
          parallelizable: false
          randomExecutionOrder: true
      environmentVariables:
        FB_REFERENCE_IMAGE_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/TestSnapshot/ReferenceImages
        IMAGE_DIFF_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/TestSnapshot/FailureDiffs
      language: ja
      region: JP
      testPlans:
        - path: MVVMArchitectureTemplateTests/MVVMArchitectureTemplate.xctestplan
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release