name: Danger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app

jobs:
  build:
    runs-on: macos-12

    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    steps:
    # チェックアウト(GitHubリポジトリからソース取得)
    - uses: actions/checkout@v3

    # Xcodeの一覧出力
    - name: Show Xcode List
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode Version
      run: xcodebuild -version

    # Gemsのインストール
    - name: Install Bundled Gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    # Gemsのキャッシュ
    - name: Cache Gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Danger実行
    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec danger