name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app

jobs:
  build:
    runs-on: macos-12

    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    steps:
    # チェックアウト(GitHubリポジトリからソース取得)
    - uses: actions/checkout@v3

    # Xcodeの一覧出力
    - name: Show Xcode List
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode Version
      run: xcodebuild -version

    # Mintインストール
    - name: Install Mint
      run: brew install mint

    # Mintで管理しているライブラリのキャッシュ
    - name: Cache Mint Packages
      uses: actions/cache@v3
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    # プロジェクトファイル生成
    - name: Generate Xcode Project
      run: |
        make generate-files
        make generate-xcodeproj

    # ビルド
    - name: Xcode Build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme MVVMArchitectureTemplate
        build

    # テスト
    - name: Xcode Test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme MVVMArchitectureTemplate
        -destination 'platform=iOS Simulator,name=iPhone 14'
        clean test