name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Show Xcode List
      run: ls /Applications | grep 'Xcode'

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
