name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Show Xcode List
      run: ls /Applications | grep 'Xcode'

    - name: Show Xcode Version
      run: xcodebuild -version

    - name: Build
      run: xcodebuild
        -scheme MVVMArchitectureTemplate
        -sdk iphonesimulator
        -configuration Debug
        build

    - name: Run tests
      run: xcodebuild
        -scheme MVVMArchitectureTemplate
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone14'
        clean test
